Repository UpendoVentures/generator-upendodnn, pull requests merged in 2023-08, with the labels that each got.

#214 update the baseUrl for API calls
  generators/spa/templates/Angular/src/app/services/items.service.ts
  generators/spa/templates/ReactJS/jsx/src/components/Items.jsx
  generators/spa/templates/VueJS/common/Scripts/ItemView.js
  generators/spa/templates/VueJS/common/Scripts/QuickSettings.js
  generators/spa/templates/common/src/Resources/scripts/QuickSettings.js
Labels: bug

#215 Fix_Hotcakes_Template_Bugs
  generators/common/src-hotcakes-hcc/creditcardgateway/Module.build
  generators/common/src-hotcakes-hcc/giftcardgateway/Module.build
  generators/common/src-hotcakes-hcc/paymentmethod/Module.build
  generators/common/src-hotcakes-hcc/taxprovider/Module.build
  generators/hcc/index.js
  generators/hcc/templates/creditcardgateway/extension.csproj
  generators/hcc/templates/giftcardgateway/extension.csproj
  generators/hcc/templates/paymentmethod/extension.csproj
  generators/hcc/templates/taxprovider/extension.csproj
Labels: bug

#217 Resolves a usability issue with auth providers
  generators/auth-provider/index.js
Labels: enhancement

#218 Resolves a minor typo
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/help-and-other-questions.md
Labels: Task

#219 Incremented the version number
  package.json
Labels: Task

#221 Update README.md
  README.md
Labels: bug

#222 Content usability updates for the readme
  README.md
Labels: enhancement

#223 Update README.md
  README.md
Labels: enhancement

#224 Update README.md
  README.md
Labels: enhancement

#225 Updates for new usage steps
  README.md
Labels: enhancement

#226 Replaced the over-complicated number system
  README.md
Labels: enhancement

#227 Update README.md
  README.md
Labels: enhancement

#229 Update README.md
  README.md
Labels: bug

#232 Updates some minor typos in the generator scripts
  generators/auth-provider/index.js
  generators/spa/templates/VueJS/Module.csproj
Labels: enhancement

#234 Features/hcc dependency
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/help-and-other-questions.md
  generators/hcc/templates/creditcardgateway/manifest.dnn
  generators/hcc/templates/giftcardgateway/manifest.dnn
  generators/hcc/templates/paymentmethod/manifest.dnn
  generators/hcc/templates/taxprovider/manifest.dnn
  generators/hcc/templates/workflow/manifest.dnn
Labels: bug

#235 fix the add project to solution issues
  generators/auth-provider/index.js
  generators/library-scheduledjob/index.js
  generators/skinobject/templates/SkinObject.csproj
Labels: bug

#239 Fix_Debug_Build_Path_for_HCC_Payment_Method_Files
  generators/common/src-hotcakes-hcc/paymentmethod/Module.build
Labels: bug

#237 Updates HCC dependency in template manifests
  generators/hcc/templates/actiondelegate/manifest.dnn
  generators/hcc/templates/creditcardgateway/manifest.dnn
  generators/hcc/templates/giftcardgateway/manifest.dnn
  generators/hcc/templates/paymentmethod/manifest.dnn
  generators/hcc/templates/taxprovider/manifest.dnn
  generators/hcc/templates/workflow/manifest.dnn
Labels: bug

#240 Updated the version number for upgrade
  package.json
Labels: Task

#241 Update README.md
  README.md
Labels: Task

#242 Update README.md
  README.md
Labels: Task

#244 Features/vs2022 support
  generators/lib/DnnGeneratorBase.js
  package.json
Labels: enhancement

#245 Update README.md
  README.md
Labels: Task

#246 Features/auto increment version
  generators/auth-provider/templates/common/Module.build
  generators/auth-provider/templates/manifest.dnn
  generators/auth-provider/templates/symbols.dnn
  generators/common/src-hotcakes-hcc/creditcardgateway/Module.build
  generators/common/src-hotcakes-hcc/giftcardgateway/Module.build
  generators/common/src-hotcakes-hcc/paymentmethod/Module.build
  generators/common/src-hotcakes-hcc/taxprovider/Module.build
  generators/common/src-library-hcc/Library.build
  generators/common/src-library/Library.build
  generators/common/src-webforms/Module.build
  generators/mvc-spa/templates/Module.build
  generators/mvc/templates/Module.build
  generators/skinobject/templates/SkinObject.build
  generators/solution/templates/Build/HccViewsetPackage.targets
  generators/solution/templates/Build/Helpers.targets
  generators/solution/templates/Build/LibraryPackage.targets
  generators/solution/templates/Build/ModulePackage.targets
  generators/solution/templates/Build/SkinPackage.targets
  generators/solution/templates/README.md
  generators/solution/templates/_Template.sln
  generators/spa/index.js
  generators/spa/templates/Angular/Module.build
  generators/spa/templates/ReactJS/common/Module.build
  generators/spa/templates/VueJS/Module.dnn
  generators/spa/templates/VueJS/common/Module.build
  generators/spa/templates/common/manifest.dnn
  package.json
Labels: enhancement

#265 Added a table of contents
  README.md
Labels: Task

#266 Update README.md
  README.md
Labels: Task

#267 Update README.md
  README.md
Labels: Task

#268 Update README.md
  README.md
Labels: Task

#276 Issues/issue 270
  generators/auth-provider/index.js
  generators/auth-provider/templates/Module.csproj
  generators/auth-provider/templates/common/packages.config
  generators/auth-provider/templates/manifest.dnn
  generators/common/csproj/_Project.csproj
  generators/common/src-library/packages.config
  generators/common/src-webforms/packages.config
  generators/hcc/index.js
  generators/hcc/templates/actiondelegate/extension.csproj
  generators/hcc/templates/actiondelegate/manifest.dnn
  generators/hcc/templates/creditcardgateway/manifest.dnn
  generators/hcc/templates/giftcardgateway/manifest.dnn
  generators/hcc/templates/paymentmethod/manifest.dnn
  generators/hcc/templates/taxprovider/manifest.dnn
  generators/hcc/templates/viewset/extension.csproj.user
  generators/hcc/templates/viewset/manifest.dnn
  generators/hcc/templates/workflow/extension.csproj
  generators/hcc/templates/workflow/manifest.dnn
  generators/lib/Constants.js
  generators/lib/versionUtil.js
  generators/library-scheduledjob/index.js
  generators/library-scheduledjob/templates/library.csproj
  generators/library-scheduledjob/templates/manifest.dnn
  generators/library/index.js
  generators/library/templates/library.csproj
  generators/library/templates/manifest.dnn
  generators/mvc-core/index.js
  generators/mvc-core/templates/manifest.dnn
  generators/mvc-spa/index.js
  generators/mvc-spa/templates/Manifest.dnn
  generators/mvc-spa/templates/Module.csproj
  generators/mvc-spa/templates/packages.config
  generators/mvc/index.js
  generators/mvc/templates/Module.csproj
  generators/mvc/templates/manifest.dnn
  generators/mvc/templates/packages.config
  generators/personabar/index.js
  generators/personabar/templates/common/manifest.dnn
  generators/skinobject/index.js
  generators/skinobject/templates/SkinObject.csproj
  generators/skinobject/templates/manifest.dnn
  generators/skinobject/templates/packages.config
  generators/solution/index.js
  generators/solution/templates/Build/SolutionReferences.targets
  generators/webforms/index.js
Labels: enhancement

#277 1.11 release
  package.json
Labels: Task
