Repository UpendoVentures/generator-upendodnn, pull requests merged in 2024-01, with the labels that each got.

#304 Permission bug
  generators/spa/templates/Vue3JS/Module.csproj
  generators/spa/templates/Vue3JS/common/Controllers/ItemsController.cs
  generators/spa/templates/Vue3JS/common/Services/ResxController.cs
Labels: bug

#307 Updated the version for release
  package.json
Labels: Task

#309 Prepping 1.12.4 release
  package.json
Labels: Task

#310 Updated dependencies
  package-lock.json
  yarn.lock
Labels: enhancement

#311 Issues/webforms dnnversion
  generators/webforms/index.js
  package.json
Labels: bug

#312 Updated dependency files
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#313 Update README.md
  README.md
Labels: Task

#314 Update README.md
  README.md
Labels: Task

#315 Update README.md
  README.md
Labels: Task
